namespace IdleBusiness.Data.Entities;

/*
Entity class to house the cash blueprint. Basic class; cash is generated by investments.
The main thing with the class is to apply interest. Maybe could have called it bank.
*/

public class Cash
{
    public User user;
    public double amount;
    public double appreciation;
}


